### ISSUE TITLE
Why separated from mars?

### ISSUE THREAD

**Issue by goldhoorn** [rock-simulation/mars_install_scripts#1]
Why this scripts are separated from mars and not inside of mars itself.

Additionally, we decided to prefix all packages like:
"simlation-mars_install_scrips" is there a reason against this?

**Comment by malter** [comment]
We moved the lib_manager out of MARS and we need the install scripts to build it without autoproj support. So we need the scripts outside to be MARS "independent" with the lib_manager.

Concerning the naming, your suggestion is very long and we are already in the project rock-simulation?
