### ISSUE TITLE
console_bridge dependency pkg_config_path issue w. x86_64-linux-gnu

### ISSUE THREAD

**Issue by HWiese1980** [rock-simulation/mars_install_scripts#12]
Hi folks,

I've got a problem installing MARS on my Ubuntu 14.04 LTS x64 machine. Here's the bug report. I hope it includes everything needed to solve the problem.
##### Problem: compiling dependency `smurf_parser` fails

Error message:

```
In file included from smurf_parser/src/SMURFParser.cpp:27:0:
smurf_parser/src/SMURFParser.h:33:30: fatal error: urdf_model/model.h: No such file or directory
 #include <urdf_model/model.h>
                          ^
compilation terminated.
make[2]: *** [CMakeFiles/smurf_parser.dir/src/SMURFParser.cpp.o] Error 1
make[1]: *** [CMakeFiles/smurf_parser.dir/all] Error 2
make: *** [all] Error 2
```

The file exists. `cmake` however can't get its path by means of `pkg-config`.
##### Probable cause:

`pkg-config` can't find dependency `console_bridge`. `console_bridge` does apparently have an issue with the environment variable `PKG_CONFIG_PATH`:

```
 $ pkg-config --cflags console_bridge
Package console_bridge was not found in the pkg-config search path.
Perhaps you should add the directory containing `console_bridge.pc'
to the PKG_CONFIG_PATH environment variable
No package 'console_bridge' found
```

In the `console_bridge` build folder after successfully running `cmake ..` and `make`:

```
$ make install
[100%] Built target console_bridge
Install the project...
-- Install configuration: "DEBUG"
-- Up-to-date: /home/xxx/install/lib/x86_64-linux-gnu/libconsole_bridge.so.0.3
-- Up-to-date: /home/xxx/install/lib/x86_64-linux-gnu/libconsole_bridge.so
-- Installing: /home/xxx/install/include
-- Installing: /home/xxx/install/include/console_bridge
-- Up-to-date: /home/xxx/install/include/console_bridge/exportdecl.h
-- Up-to-date: /home/xxx/install/include/console_bridge/console.h
-- Up-to-date: /home/xxx/install/lib/x86_64-linux-gnu/console_bridge/cmake/console_bridge-config.cmake
-- Up-to-date: /home/xxx/install/lib/x86_64-linux-gnu/console_bridge/cmake/console_bridge-config-version.cmake
-- Up-to-date: /home/xxx/install/lib/x86_64-linux-gnu/pkgconfig/console_bridge.pc
```
- my original `PKG_CONFIG_PATH` only includes `/home/xxx/install/lib/pkgconfig`
- console_bridge.pc resides in the path `/home/xxx/install/lib/x86_64-linux-gnu/pkgconfig`
- the **x86_64-linux-gnu** part seems to be a problem
- this path isn't part of PKG_CONFIG_PATH
- adding this path manually to PKG_CONFIG_PATH solves the problem
##### Branches:

`smurf_parser` and `console_bridge` working trees are at `origin/master` as of today.

If you need any further info I'll see what I can find.

**Comment by kavonszadkowski** [comment]
Hi,

so it turns out that the ROS guys have done quite a bit of work lately on their CMake configuration etc. 

There are now forks of the ROS dependencies that we use which we can update when we make a new MARS release and they are now used for the install scripts. Try again. Everything should work gracefully now.
